### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by johnny-mac** [kinvolk/firefox-flatpak#8]
Hi, is this project dead??? I came across a webpage that gave me this link but this link doesn't seem to work -.-

https://firefox-flatpak.mojefedora.cz/

flatpak remote-add --from org.mozilla.FirefoxRepo https://firefox-flatpak.mojefedora.cz/org.mozilla.FirefoxRepo.flatpakrepo

**Comment by krnowak** [comment]
We are not working on it any more, you may want to have a look at https://github.com/endlessm/firefox-flatpak. Hopefully will work for you.
