### ISSUE TITLE
The gnome extension is not supported

### ISSUE THREAD

**Issue by dinhokusanagi** [kinvolk/firefox-flatpak#9]
![Screenshot from 2020-05-05 19-59-16](https://user-images.githubusercontent.com/43162113/81132796-04c88200-8f26-11ea-95cd-d0c7f06f93de.png)
![Captura de tela de 2020-05-05 14-28-00](https://user-images.githubusercontent.com/43162113/81132821-13af3480-8f26-11ea-81ec-abf11dc75702.png)

**Comment by chrskhl** [comment]
Sorry, we should have archived this repo as it's not active. I'm not sure exactly where to file it but we've not touched the repo in years.
